name: great_places
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-246.0.dev <4.0.0'

dependencies:
  adaptive_action_sheet: ^2.0.3
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  google_maps_flutter: ^2.3.1
  http: ^1.1.0
  image_picker: ^1.0.0
  location: ^5.0.0
  path: ^1.8.3
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.4
  sqflite: ^2.2.8+4
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/no_place.jpg
    - assets/images/auth-img-01.jpg
    - assets/images/profileImage.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
